### ISSUE TITLE
Traffic Simulator guide agent to totally wrong way

### ISSUE THREAD

**Issue by okanasik** [roborescue/rcrs-server#1]
On map "day3/VC2" of world 2013, when an agent try to move from 52634 to 4462, it would be thrown into the building 52698. But actually the MoveCommand has path [52634, 724, 4462], and there is no blockade at all.
In the attached picture, the blue line shows the ideal path, and the pink line is the actual position history return by traffic simulator.
![pic](https://user-images.githubusercontent.com/1243277/30742553-451060ec-9fa2-11e7-98e6-ba3b77bbb854.PNG)

Creator: Hongyu Zhao (https://sourceforge.net/p/roborescue/bugs/113/)

**Comment by kandeh** [comment]
According to my review and tests, the problem is caused from _TrafficSimulator.getBestPoint_ method.
The idea behind this method looks good, but in some cases causes problems like this issue, and I think it is not that necessary.

I changed (803a99512ceb9809ec91b8ca2df915fb1071d95c) this method to simply return the given edge's center, and the problem was solved, but I worry about side effects. I did a lot of tests and there was no problem.

![p](https://user-images.githubusercontent.com/11750680/39661016-3e954a4c-5060-11e8-9575-b231d74499e0.png)

@alim1369, You added this method via commit 9ae64842af35f179cc762aefbd94a1c931277d7e . What do you think about it?

 @armanaxh @amiraslanaslani, please do some tests (with and without blockades) and report.

**Comment by gnardin** [comment]
Fix applied.
