### ISSUE TITLE
The bed continues occupied

### ISSUE THREAD

**Issue by PG023** [roborescue/rcrs-server#46]
I want to treat the civilian who has suffered more critical damage. Therefore, I tried to move the civilian who is already in bed by the "load" command.
But, the following happens:
* Treatment for another civilian in the queue does not start because the loaded civilian continue to occupy the bed.
* The loaded civilian's Damage property increases gradually at each step.
* The bed continues occupied if the loaded civilian's HP property reaches 0.

**Comment by gnardin** [comment]
**Treatment for another civilian in the queue does not start because the loaded civilian continue to occupy the bed.**
What do you mean by Loaded Civilian? We assume Loaded Civilian is on the Ambulance Team and it should not be occupying a bed. Is it what is happening?

**The loaded civilian's Damage property increases gradually at each step.**
If the civilian has not been unloaded from the Ambulance or if there is no bed available, the Damage will continues to increase.

**The bed continues occupied if the loaded civilian's HP property reaches 0.**
This seems a bug. We will check it to see if we find the problem.

Could you please provide more information and share the map+scenario where you have observed these issues?

Thank you,

**Comment by PG023** [comment]
Thank you for your prompt reply.
Sorry for the lack of information.

I experimented on a modified rsrs-server/maps/gml/test. The attached file is the map+scenario and the rescue.log of the experiment.
[The_bed_continue_occupied.zip](https://github.com/roborescue/rcrs-server/files/6545768/The_bed_continue_occupied.zip)

I tried to move a Civilian to outside of the bed in the following steps:
1. When Civilian A unloaded by the Ambulance Team on Refuge, Civilian A occupied the bed and got treatment.
2. Civilian B was unloaded by Ambulance Team then added to the queue.
3. Civilian A was loaded by Ambulance Team.

**Loaded Civilian** is Civilian A above.
The attached file hp.pdf shows the change in Civilian's hp in this experiment.
[hp.pdf](https://github.com/roborescue/rcrs-server/files/6545771/hp.pdf)
Is it prohibited to load Civilians during treatment? I want to treat the Civilian who has suffered more critical damage than the Civilian already in bed.

**(1)The loaded Civilian's Damage property increases gradually at each step.**
**(2)The bed continues occupied if the loaded Civilian's HP property reaches 0.**
I am sorry I didn't explain it enough.
The continuous increase of damage of Civilian A (1) caused (2). In other words, problems (1) and (2) can say the same problem.

**Comment by ffaraji** [comment]
misc simulator is updated to handle load command inside a refuge to load a victim when is in the waiting list or is on a bed.
Could you please rerun the simulation with that same condition (scenario + code ) to check it .

Thank you

**Comment by PG023** [comment]
I'm sorry for the late reply.
I  confirm that civilians' HP changed as expected in the refuge.
[hp_damage_in_refuge.pdf](https://github.com/roborescue/rcrs-server/files/6746022/hp_damage_in_refuge.pdf)
Thank you.

**Comment by gnardin** [comment]
Dear @PG023 
Thank you for the update.
