### ISSUE TITLE
Problems when trying to start the server

### ISSUE THREAD

**Issue by charon-1-1** [roborescue/rcrs-server#60]
When we use the command `bash start.sh` , the terminal keeps showing "Still waiting for 'Listening for connections'...". We tried for a long time but couldn't figure out what the problem was

**Comment by gnardin** [comment]
@charon-1-1 
I tested running the simulator on my own computer and it does work fine. Can you please provide us further information about the environment (computer, OS, Java version, etc) where you are trying to run the simulator? Additionally, please share the log files that you can find on the `logs` directory, so we can help you solve the issue.

**Comment by charon-1-1** [comment]
Thank you very much for your help！
computer: HP
OS: Ubuntu 18.04.6 LTS （virtual machine）
Java version: openjdk version "17.0.2" 2022-01-18
gardle version: Gradle 4.4.1
git version 2.17.1
git version 2.17.1
logs:
[logs.zip](https://github.com/roborescue/rcrs-server/files/8252488/logs.zip)
![error](https://user-images.githubusercontent.com/67632791/158362576-b8330656-91d3-4517-b42f-7eab014b887e.png)

**Comment by modaresimr** [comment]
@gnardin 
I think the problem is with the config of types.cfgwhich mentioned ../jars

**Comment by gnardin** [comment]
@charon-1-1 and @modaresimr

Looking at the log files, the exception is related to Java. See the snippet I copied from `kernel-out.log` file.

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)`

@charon-1-1 
I have a similar configuration than yours. The only difference is the Ubuntu version, I am using version 20.04. But the Java and Gradle are the same. In my computer it does not cause any error.

I noticed, however, that you are probably using an older version of the simulator (v1.5) since you are launching the `start.sh` script from the `boot` directory while in the new version (v2.0) the script is launched from the `scripts` directory.

The older version of the simulator (v1.5) is not compatible with Java 17. You can switch back to Java 11 or you can update to the new version of the simulator. You can clone the new version of the simulator using `git clone https://github.com/roborescue/rcrs-server.git`.

Please let us know if the problem persists.

**Comment by charon-1-1** [comment]
Thank you for your reply, actually we have tried the new server, we have tried many on Ubuntu20.04, but we ran into the same problem. It was strange that the team members could run the server successfully with the same operation in the same environment as us, but I and several other members had this problem and were bothered by it for a long time.
Here is the log file from the new server:
[logs.zip](https://github.com/roborescue/rcrs-server/files/8253115/logs.zip)

**Comment by gnardin** [comment]
@charon-1-1 
It seems it is something related to your environment setup.

Can you please install the OpenJDK 17 JDK as indicated below?
               `sudo apt install openjdk-17-jdk`

You may have the headless, but not the JDK installed.

After installing, test on the new simulator since the old one is not tested with the Java 17.

Please let us know if the problem persists.

**Comment by gnardin** [comment]
Please let us know if you have any further problem.
