### ISSUE TITLE
Why time step is slow?

### ISSUE THREAD

**Issue by swhaKo** [roborescue/rcrs-server#9]
When I run the simulator based on introduction manual(start.sh -m ../maps/gml/Kobe2013/maps -c ../maps/gml/Kobe2013/config), it takes 5 seconds for each time steps.
Does it usually take five seconds for each step? Is there a way to change it?

**Comment by gnardin** [comment]
Dear @swhaKo,
The simulator takes 5 seconds to run each step because this map has many elements (i.e., buildings and roads) and many agents too. We may improve the simulator performance in the future, but this is the usual timestep running time for this map.
I realized that suggesting this map as a testing map is not a good approach for beginners. Thus, I changed the default map to the ```test``` map that is much smaller. However, if you still want to run the ```kobe``` map, you can use the command line ```./start.sh ../maps/gml/kobe```. You do not need to set the ```map``` and ```config``` directories separately as you mentioned in your message.
I have also uploaded several other maps into the ```maps/gml``` directory. You may try these other maps to see their performance. For example, the San Francisco map ```maps/gml/sf``` takes only 3 seconds per timestep in my machine.
I also realized there is no intermediary size map. We have very large and very small maps. I will create an issue for us to develop an intermediary size map.

**Comment by swhaKo** [comment]
Thank you very much for your kind answers! In addition, I can not find San Francisco map in gml/sf.
And I think that make intermediary sized maps is a good idea. It is really helpful.

**Comment by gnardin** [comment]
Dear @swhaKo,
Please ```git pull``` the ```rcrs-server``` project again. I had included several maps after you opened the issue. If you still cannot see it, please let me know.

**Comment by swhaKo** [comment]
Thank you very much for your kind answers! It's solved.
